package com.example.earthquakes.entities

data class EarthquakeProperties(
    val mag: Double,
    val place: String,
    val time: Long,
    val updated: Long,
    val tz: String?,
    val url: String,
    val detail: String,
    val felt: Int?,
    val cdi: Double?,
    val mmi: Double?,
    val alert: String?,
    val status: String,
    val tsunami: Int,
    val sig: Int,
    val net: String,
    val code: String,
    val ids: String,
    val sources: String,
    val types: String,
    val nst: Int?,
    val dmin: Double?,
    val rms: Double,
    val gap: Double?,
    val magType: String,
    val type: String,
    val title: String
)
